// Code generated by chMenu
namespace CherryTree {

    public class chUnityTags {
		public const string UNTAGGED = "Untagged";
		public const string RESPAWN = "Respawn";
		public const string FINISH = "Finish";
		public const string EDITORONLY = "EditorOnly";
		public const string MAINCAMERA = "MainCamera";
		public const string PLAYER = "Player";
		public const string GAMECONTROLLER = "GameController";
		public const string AUDIOSFX = "AudioSFX";
		public const string AUDIOBGM = "AudioBGM";
		public const string TEST = "Test";
	}

}
